server:
  port: 8001

spring:
  application:
    name: cloud-payment-service       # 应用名称, 注册到eureka也是使用该名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包, 5.7之后需要加上SSL
    url: jdbc:mysql://localhost:3306/springcloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # 配置zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1     # 采样值, 0-1之间, 1表示全部采样

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true    # 将自己注册到 eureka server, 默认为true
    fetch-registry: true      # 从eureka server抓取已有的注册信息, 默认为true
    service-url:
      #设置Eureka Server地址, 查询服务和注册服务都需要依赖这个地址, http:// 必须写
      # defaultZone: http://localhost:7001/eureka   # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001      # 修改Eureka中心显示的实例名称, 隐藏主机名
    prefer-ip-address: true       # 显示ip