server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    # 配置nacos
    nacos:
      discovery:
        server-addr: localhost:8848

    # 配置Sentinel
    sentinel:
      transport:
        dashboard: localhost:8858   # 控制台端口
        port: 8719                  # 服务端口
        client-ip: 192.168.1.103        # docker安装Sentinel需要配置

management:
  endpoints:
    web:
      exposure:
        include: '*'

