server:
  port: 8001

spring:
  application:
    name: cloud-payment-service       # 应用名称, 注册到eureka也是使用该名称

eureka:
  client:
    register-with-eureka: true    # 将自己注册到 eureka server, 默认为true
    fetch-registry: true      # 从eureka server抓取已有的注册信息, 默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
